### ISSUE TITLE
Is this driver dead?

### ISSUE THREAD

**Issue by breathe** [fauna/faunadb-swift#116]
Hi -- curious if this driver is dead ...?

I just want to bump this driver and suggest that with the emergence of swift-ui -- I think it is perhaps worth re-investing in this driver.

There is _definitely_ room in the apple ecosystem for a super high quality, easy to use, zero-management data-layer for swift-ui ...

A lot of new folks jumping into swift-ui googling 'what's a good api/data store for swift-ui' or some such.  I think it would be a boon to many of those developers if one of the results they found during that search was this driver and faunadb.

**Comment by evbruno** [comment]
Would you consider working with Grapqhl and FaunaDB or the FQL/driver is the "main argument" on adopting Fauna ?

**Comment by breathe** [comment]
@evbruno I would consider using the faunadb graphql api assuming that I can express all the interactions I need to support via faunadb auto-generated graphql api without having to overly contort my UI code ... 

I've done some previous investigation of the faunadb graphql api -- but not used it yet for anything.  A clean way to easily support upsert's seemed like it was missing when I last looked ...  I want to have the simplest possible interface to the datastore from my UI -- and ensure that application data layer is easily organized in a way that will work well for declarative UI.  

Upsert seems like a pretty convenient operation for simplifying the general programming model for CRUD for use in declarative UI while maintaining straightforward/clear ways to solve problems in a clean way (in my previous experiences) ...  So I tend to look for 'how would upsert look' when evaluating a data management api ... 

I see a partialUpdateMutation feature in preview now -- which might help ... -- 
https://docs.fauna.com/fauna/current/api/graphql/previews/partial_update_mutation 

Feature seems interesting -- achieving the same with a postgres jsonb store requires either a whole bunch of hideous jsonb partial-update syntax or requires wrapping things carefully in serializable transactions to avoid read/write races -- so I appreciate this operation.  But this op doesn't appear like it would directly support the ability for upsert to create an entity that doesn't yet exist when ID! is nil -- ?  I think my ideal interface would consolidate create and update this way -- seems like it would be especially convenient when mutating embedded entities ...

If an embedded type is an array -- is there a way to do a partial update to add a new element to that array without sending a payload that contains all array elements?

I'd really like mutations (for say -- @embedded types) to follow some form of consistent convention ...

```
upsert({some_collection, some_owner_id, { some_embedded_array: {prop1: "foo"}})
upsert({some_collection, some_owner_id: { some_embedded_array: {id: "foo", prop2: "bar"}})
upsert({some_collection, some_owner_id: { some_embedded_array: {id: "foo", prop1: "bar1"}})

// some_owner_id:
{
...,
some_embedded_array: [
  {id: "autogenerated", prop1: "foo"},
  {id: "foo", prop2: "bar", prop1: "bar1"}
  ]
}
```
